### ISSUE TITLE
!!PCRC spec

### ISSUE THREAD

**Issue by JohanVonElectrum** [Fallen-Breath/PCRC#1]
![imagen](https://user-images.githubusercontent.com/25396028/75373472-aa2dfc80-58ca-11ea-8366-f1d768a0fc83.png)
```!!PCRC spec``` crash (bot is gm3 and op)

**Comment by JohanVonElectrum** [comment]
![imagen](https://user-images.githubusercontent.com/25396028/75374061-dc8c2980-58cb-11ea-83d3-0e3fd08307cf.png)
Other error with ```!!PCRC spec```

**Comment by Fallen-Breath** [comment]
do u have steps or more details about how to reproduce this bug?

**Comment by Fallen-Breath** [comment]
and make sure u have good network connection to the server

**Comment by JohanVonElectrum** [comment]
I have the game hosted in a dedicated server localhost. Details... Justs execute and write the command.

**Comment by JohanVonElectrum** [comment]
Other commands works.

**Comment by Fallen-Breath** [comment]
Does it still occur in the latest release?
