### ISSUE TITLE
1.16.4 packets error

### ISSUE THREAD

**Issue by kkosteck** [Fallen-Breath/PCRC#16]
Error when starting PCRC. I tried this on linux and windows both connected to server with carpet and vanilla - same issue in all of situations. 
Log:

> [2021-01-03 14:57:40 INFO] [PCRC-Recorder] Starting PCRC
> [2021-01-03 14:57:40 INFO] [PCRC-Recorder] Allow versions of the server: {736, 578, 335, 751, 753, 498, 754, 340}
> [2021-01-03 14:57:40 INFO] [PCRC] Recorder started, success = True
> [2021-01-03 14:57:40 INFO] [PCRC-Recorder] Allow versions of the server: {754}
> [2021-01-03 14:57:40 INFO] [PCRC-Recorder] Connecting using protocol version 754, mc version = 1.16.4
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] Connected to the server, start recording
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] [Thread Chat] Chat thread started
> [2021-01-03 14:57:41 ERROR] [PCRC-Recorder] Error when processing packet
> [2021-01-03 14:57:41 ERROR] [PCRC-Recorder] Packet id = 2; Packet name = Spawn Living Entity
> [2021-01-03 14:57:41 ERROR] [PCRC-Recorder] Exception in network thread: Server sent a varint that was too big!
> [2021-01-03 14:57:41 DEBUG] [PCRC-Recorder] Traceback (most recent call last):
>   File "PCRC\utils\pycraft\networking\connection.py", line 564, in run
>   File "PCRC\utils\pycraft\networking\connection.py", line 603, in _run
>   File "PCRC\utils\pycraft\networking\connection.py", line 540, in _react
>   File "PCRC\utils\pycraft\networking\packets\packet_listener.py", line 15, in call_packet
>   File "PCRC\utils\recorder.py", line 110, in onPacketReceived
>   File "PCRC\utils\recorder.py", line 234, in processPacketData
>   File "PCRC\utils\packet_processor.py", line 29, in process
>   File "PCRC\utils\packet_processor.py", line 174, in _process
>   File "PCRC\utils\packet_processor.py", line 106, in processSpawnEntity
>   File "PCRC\utils\SARC\packet.py", line 50, in read_varint
> OSError: Server sent a varint that was too big!
> 
> [2021-01-03 14:57:41 ERROR] [PCRC-Recorder] Stopping the recorder since PCRC has not been stopped by user
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] Stopping PCRC, restart = True, by_user = False
> [2021-01-03 14:57:41 WARN] [PCRC-Recorder] [Thread File] Size of "recording.tmcpr" too small (0.00KB < 10.00KB), abort creating replay file
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] [Thread File] File operations finished, disconnect now
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] [Thread File] PCRC stopped
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] [Thread Chat] Chat thread stopped
> [2021-01-03 14:57:41 INFO] [PCRC-Recorder] [Thread File] ---------------------------------------

**Comment by kkosteck** [comment]
Apparently there is something wrong only with one of my accounts. I tried with two other accounts and it works perfectly fine.

**Comment by Fallen-Breath** [comment]
Does it still occur in the latest PCRC version?
