### ISSUE TITLE
加载录像文件卡在loading terrain.

### ISSUE THREAD

**Issue by XYSummerT** [Fallen-Breath/PCRC#17]
使用离线模式进行录制。加载录像文件是卡在loading terrain，会反复弹出来然后消失(正版不知道，因为没有多余的正版号

**Comment by Fallen-Breath** [comment]
请给出具体详细的复现方法

**Comment by XYSummerT** [comment]
设置里面设置的是版本1.16.1，离线模式，名字"bot_PCRC"，运行环境在windows10 1909+python3.8和 ubuntu server19.10+python3.8都试过。用MCDR启动PCRC和直接启动PCRC也都试过。在输入stop后，把录像文件丢到客户端里加载，会卡在loading terrain。 但是用客户端的replay却没有问题。

https://user-images.githubusercontent.com/63708224/108721953-8a70f900-755d-11eb-8fd9-4742dea9c1a5.mp4

**Comment by cateast222** [comment]
在正版账号测试下也是如此

**Comment by XYSummerT** [comment]
。。。
