### ISSUE TITLE
!!PCRC 游戏内命令无效

### ISSUE THREAD

**Issue by ghost** [Fallen-Breath/PCRC#2]
[2020-03-30_19-37-59.zip](https://github.com/Fallen-Breath/PCRC/files/4405956/2020-03-30_19-37-59.zip)

**Comment by Fallen-Breath** [comment]
你的服务端种类/服务端版本是什么？如果不是原版的话PCRC可能没有解析成功聊天数据包

**Comment by ghost** [comment]
> 你的服务端种类/服务端版本是什么？如果不是原版的话PCRC可能没有解析成功聊天数据包

PaperMc

**Comment by Fallen-Breath** [comment]
paper给的数据量太少了，支持paper相关的服务端不在计划中。用后台操作吧
