### ISSUE TITLE
[SUGGESTION] Stream instead of recording into a file

### ISSUE THREAD

**Issue by alekitopi** [Fallen-Breath/PCRC#23]
I think that this could be adapted so instead of saving the buffer into a file, it can be streamed to a local server so it can be used as a ingame cam and create 24/7 Minecraft Streams.

**Comment by Fallen-Breath** [comment]
"streamed to a local server" what content do you expect to be streamed? PCRC only records binary packet data stream, which is not possible to be simply converted into a video stream

**Comment by alekitopi** [comment]
With that I mean that instead of creating a video file with the data stream, send it to a external server (RMTP, for example).

**Comment by Fallen-Breath** [comment]
PCRC does not have the ability to create a video or a video stream or a RMTP stream

And you didn't answer my question too https://github.com/Fallen-Breath/PCRC/issues/23#issuecomment-1157215789
