### ISSUE TITLE
Please add the ability to disable the "replay mod" in the config.

### ISSUE THREAD

**Issue by Vinsard** [Fallen-Breath/PCRC#28]
Please add the ability to disable the "replay mod" in the config so that the program works as an afk-player.

**Comment by Fallen-Breath** [comment]
Why not just run the dependency project [pycraft](https://github.com/ammaraskar/pyCraft) directly?

**Comment by Vinsard** [comment]
I don't have the necessary knowledge to do this. I can just open an .exe program on windows 10, as well as slightly configure programs in the config file.

**Comment by Fallen-Breath** [comment]
There are a lot of alternative to this kind of CLI based simple Minecraft client, no reason to just stick on PCRC
