### ISSUE TITLE
Is that already supported in Minecraft 1.15.2?

### ISSUE THREAD

**Issue by Fjunhere** [Fallen-Breath/PCRC#3]
![Capture](https://user-images.githubusercontent.com/63272290/78621647-ac19b100-78b5-11ea-8c36-939fe5c8e3ba.PNG)

i use local server in MCDR with PCRC Plugin .

i know replay mod did not upgrade to 1.15.2 but it says that PCRC can run in 1.15.2 .

maybe here's some trouble with that ?

**Comment by Fallen-Breath** [comment]
you need a extra bungeecord server with viaversion plugin for PCRC to use 1.14.4 protocol to connect to 1.15.2 server

**Comment by Fjunhere** [comment]
oh yep i forgot that XD
