### ISSUE TITLE
PCRC PCRC keeps outputting "Set self's position to PositionAndLook"

### ISSUE THREAD

**Issue by CUX-LI** [Fallen-Breath/PCRC#30]
PCRC keeps outputting "[Networking Thread/INFO]: Set self's position to PositionAndLook (xyz position information)" and there is no output for keywords entered in the game, but it can be reborn through keywords

PCRC持续输出“[Networking Thread/INFO]: Set self's position to PositionAndLook(xyz位置信息)”且游戏中输入关键词无输出，但可以通过关键词重生

[2022-08-13-4.zip](https://github.com/Fallen-Breath/PCRC/files/9330503/2022-08-13-4.zip)

**Comment by CUX-LI** [comment]
Where is the problem, the Python version is 3.10.6, the server version is 1.18.2, and the video can be output normally

这是哪里的问题，Python版本为3.10.6，服务器版本为1.18.2，可以正常输出录像

**Comment by CUX-LI** [comment]
The problem has been solved: the server has a built-in login plugin, but the PCRC fake player is not registered and is repeatedly relocated by the plugin

问题已解决：服务器内置了登录插件，而PCRC假玩家没有注册，被插件反复重定位

**Comment by CUX-LI** [comment]
In a similar situation like mine, I give a suggestion to the big guy: set a message (usually / command) to be sent when logging in to the server every time you log in to automatically log in. Some installation login plugins require manual input of instructions to register.

就我这种类似情况，我给大佬提个建议：在每次登录服务器的时候设置一个登录时发送的消息（一般就是/指令这样）用来自动登录某些安装登录插件需要手动输指令注册登录的那种服务器

**Comment by Fallen-Breath** [comment]
非原版服务器的功能千奇百怪，这次需要输入指令登录，下次可能又需要在物品栏中操作物品上服，是做不到适配所有情况的。对于该 issue 所述情况，你完全可以在控制台手动让 PCRC 发送聊天信息来登录。

以及请不要使用机翻。
