### ISSUE TITLE
回放时，时间仍然变化

### ISSUE THREAD

**Issue by HarlanWang** [Fallen-Breath/PCRC#31]
使用PCRC1.0以上版本，无论是连接开放局域网的单人游戏，或是服务端，回放文件并未按照config文件中设定的固定游戏时间。回放中太阳等依旧东升西落而不是固定不动。
读取回放文件的客户端为安装fabric的1.16.5版本

**Comment by HarlanWang** [comment]
0.10.0alpha版本经测试没有问题

**Comment by Fallen-Breath** [comment]
已于 [v1.4.0](https://github.com/Fallen-Breath/PCRC/releases/tag/v1.4.0) 修复
