### ISSUE TITLE
尝试使用微软登录时提示unauthorized_client错误

### ISSUE THREAD

**Issue by shinyashen** [Fallen-Breath/PCRC#32]
如题，将PCRC作为MCDR插件启动后，第一次尝试开启PCRC功能进行登录时，打开控制台提供的网址后，登录网站抛出unauthorized_client异常，具体如下：
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by Fallen-Breath** [comment]
无法复现，我这边 PCRC 工作正常
