### ISSUE TITLE
无法执行玩家发送的命令

### ISSUE THREAD

**Issue by cxzlw** [Fallen-Breath/PCRC#34]
![image](https://user-images.githubusercontent.com/55052188/210054174-03a1e0c5-abc6-493e-90ee-b93f45e1d3e7.png)
服务端是1.18.2的spigot
正常mc也是1.18.2版本
bot无法接受或执行玩家发送的命令
![image](https://user-images.githubusercontent.com/55052188/210054260-4e774a8e-7b38-49af-bd13-315a9a6ee587.png)
白名单已加入玩家用户名

**Comment by cxzlw** [comment]
刚刚关闭的那个issue并不完整，似乎大部分消息都是无法解析的

**Comment by Fallen-Breath** [comment]
与 #2 为同类型问题：spigot 为非原版，聊天文本中所含的信息过少，无法获取玩家名。相关服务端的支持不在计划之中

**Comment by cxzlw** [comment]
> 与 #2 为同类型问题：spigot 为非原版，聊天文本中所含的信息过少，无法获取玩家名。相关服务端的支持不在计划之中

明白了
