### ISSUE TITLE
1.15.2在游戏内无法使用聊天触发命令

### ISSUE THREAD

**Issue by li4tlEShr1Mp** [Fallen-Breath/PCRC#7]
大大，我在游戏内无法使用聊天触发命令
PCRC后台输!!PCRC有反应
白名单设置的是false
设置true添加了ID也不行
服务器是Spigot端
![1](https://user-images.githubusercontent.com/61986408/80597434-68e8d300-8a5a-11ea-813f-cd40eb3afe49.png)

**Comment by li4tlEShr1Mp** [comment]
服务器的消息能够识别
![2](https://user-images.githubusercontent.com/61986408/80599551-b0249300-8a5d-11ea-9c6a-d326a029046c.png)

**Comment by Fallen-Breath** [comment]
pcrc的游戏内命令只支持原版端
