### ISSUE TITLE
在MCDR里 "remove_items": false 以及其他命令不生效

### ISSUE THREAD

**Issue by Redlnn** [Fallen-Breath/PCRC#9]
系统: Centos 7.8.2003
Pyhton版本: 3.7.7
Java版本: openjdk 1.8.0_252
服务端版本: Paperclip-284 (1.15.2) & 1.15.2 原版服务端
MCDR版本: 0.9.2-alpha
PCRC版本: 0.10.0-alpha
PCRC-MCDR版本: 直接clone仓库，d3b891a commit
现象: 仅有`!!PCRC start`和`!!PCRC stop`有效果，其他命令组合都没有反馈（包括`!!PCRC`），也不生效。`config.json`里设置`"remove_items": false`也不生效，录制出来的回放并没有掉落物，也没有飞行中的箭、投掷药水、末影珍珠。【以上命令均是在控制台中输入】

**Comment by Fallen-Breath** [comment]
见readme，只保证对原版端有支持

**Comment by Redlnn** [comment]
原版端也测试了，也用不了。

> 服务端版本: Paperclip-284 (1.15.2) & 1.15.2 原版服务端

**Comment by Redlnn** [comment]
![image](https://user-images.githubusercontent.com/41742767/82118711-9c8e6180-97ab-11ea-9132-3b58c1862f24.png)
